#!/usr/bin/env node
// Build the React Native target for @dtelecom/vodozemac-wasm.
//
// Hermes V1 (React Native 0.84+) supports WebAssembly, but RN's bundler
// (Metro) doesn't have a stable "asset URL" for .wasm files the way Vite
// / webpack do. So we generate a self-contained pkg-rn/ that base64-
// embeds the WASM bytes alongside a stripped-down copy of the wasm-
// bindgen JS glue. The host imports the package normally; the WASM is
// instantiated from in-memory bytes on first init() call.
//
// Inputs (must already exist; run `npm run build:web` first):
//   pkg-web/dtelecom_vodozemac_wasm.js
//   pkg-web/dtelecom_vodozemac_wasm.d.ts
//   pkg-web/dtelecom_vodozemac_wasm_bg.wasm
//
// Outputs:
//   pkg-rn/dtelecom_vodozemac_wasm.js   — pkg-web glue, __wbg_init + __wbg_load
//                                          stripped (they use fetch + import.meta.url
//                                          which Metro / Hermes can't resolve)
//   pkg-rn/dtelecom_vodozemac_wasm.d.ts — verbatim copy of pkg-web types
//   pkg-rn/wasm-base64.js               — base64-encoded WASM bytes as a string
//   pkg-rn/index.js                     — entrypoint: re-exports + async default init()
//   pkg-rn/index.d.ts                   — entrypoint types
//   pkg-rn/package.json                 — module metadata pointing at index.js

import { readFileSync, writeFileSync, mkdirSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const pkgWeb = resolve(root, "pkg-web");
const pkgRn = resolve(root, "pkg-rn");

if (!existsSync(resolve(pkgWeb, "dtelecom_vodozemac_wasm.js"))) {
  console.error("error: pkg-web/ not built. Run `npm run build:web` first.");
  process.exit(1);
}

mkdirSync(pkgRn, { recursive: true });

// ── 1. Strip browser-only loader paths from the JS glue ────────────────────

const glueSrc = readFileSync(
  resolve(pkgWeb, "dtelecom_vodozemac_wasm.js"),
  "utf8",
);

/**
 * Remove a top-level function declaration by name. Matches `async function`
 * and `function`; consumes the full body via brace-matching.
 */
function stripFunction(src, name) {
  const re = new RegExp(`(?:^|\\n)(?:async\\s+)?function ${name}\\b[^{]*\\{`);
  const m = re.exec(src);
  if (!m) return src;
  let depth = 1;
  let i = m.index + m[0].length;
  while (i < src.length && depth > 0) {
    const ch = src[i];
    if (ch === "{") depth++;
    else if (ch === "}") depth--;
    i++;
  }
  return src.slice(0, m.index) + src.slice(i);
}

let stripped = glueSrc;
// __wbg_load uses fetch + WebAssembly.instantiateStreaming + Response-shape
// checks. None of that exists or is reachable in RN. Only __wbg_init calls
// it, and we strip __wbg_init too.
stripped = stripFunction(stripped, "__wbg_load");
// __wbg_init uses new URL(.., import.meta.url) + fetch(URL). Both are
// browser-resolution paths; Metro can't satisfy them. We replace this
// loader entirely with the base64 path in index.js.
stripped = stripFunction(stripped, "__wbg_init");

// Rewrite the final export to drop the missing __wbg_init reference.
// The original line is:  export { initSync, __wbg_init as default };
stripped = stripped.replace(
  /export\s*\{\s*initSync\s*,\s*__wbg_init\s+as\s+default\s*\}\s*;?\s*$/m,
  "export { initSync };",
);

writeFileSync(
  resolve(pkgRn, "dtelecom_vodozemac_wasm.js"),
  stripped,
  "utf8",
);

// Types stay identical — same class shapes; the default export becomes our
// own init(), which we declare separately in index.d.ts.
const dts = readFileSync(
  resolve(pkgWeb, "dtelecom_vodozemac_wasm.d.ts"),
  "utf8",
);
// Drop the default-export declaration from the inner .d.ts to match the
// trimmed .js (it referenced the deleted __wbg_init). The named exports
// (Account, Session, InboundResult, initSync) stay.
const dtsTrimmed = dts
  .replace(/export\s+default\s+function[\s\S]*?(?=\nexport|$)/g, "")
  .replace(/\nexport\s+\{\s*initSync[^}]*as\s+default[^}]*\}\s*;?/g, "");
writeFileSync(
  resolve(pkgRn, "dtelecom_vodozemac_wasm.d.ts"),
  dtsTrimmed,
  "utf8",
);

// ── 2. Embed the WASM as base64 ────────────────────────────────────────────

const wasmBytes = readFileSync(
  resolve(pkgWeb, "dtelecom_vodozemac_wasm_bg.wasm"),
);
const wasmBase64 = wasmBytes.toString("base64");
const wasmKb = (wasmBytes.length / 1024).toFixed(1);
const b64Kb = (wasmBase64.length / 1024).toFixed(1);

writeFileSync(
  resolve(pkgRn, "wasm-base64.js"),
  `// AUTOGENERATED — see scripts/build-rn.mjs. Do not edit.
// Source: pkg-web/dtelecom_vodozemac_wasm_bg.wasm (${wasmKb} KB raw, ${b64Kb} KB base64).
export const WASM_BASE64 = "${wasmBase64}";
`,
  "utf8",
);
writeFileSync(
  resolve(pkgRn, "wasm-base64.d.ts"),
  `export declare const WASM_BASE64: string;\n`,
  "utf8",
);

// ── 3. Entrypoint that bundles init() over the embedded bytes ──────────────

writeFileSync(
  resolve(pkgRn, "index.js"),
  `// React Native entrypoint for @dtelecom/vodozemac-wasm. Mirrors the
// pkg-web public shape: a default async \`init()\` plus named exports for
// Account / Session / InboundResult / initSync. Hermes V1 (RN 0.84+)
// supports WebAssembly natively; the only RN-specific bit is loading the
// .wasm bytes from a base64 constant (Metro doesn't ship .wasm as a
// fetch-able asset URL).

import { initSync } from "./dtelecom_vodozemac_wasm.js";
import { WASM_BASE64 } from "./wasm-base64.js";

export { Account, Session, InboundResult, initSync } from "./dtelecom_vodozemac_wasm.js";

function base64ToBytes(b64) {
  // Hermes ships atob; avoid Buffer to stay dependency-free.
  const bin = atob(b64);
  const out = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
  return out;
}

let initPromise = null;
async function init() {
  if (initPromise) return initPromise;
  initPromise = (async () => {
    initSync({ module: base64ToBytes(WASM_BASE64) });
  })();
  return initPromise;
}

export default init;
`,
  "utf8",
);

writeFileSync(
  resolve(pkgRn, "index.d.ts"),
  `export { Account, Session, InboundResult, initSync } from "./dtelecom_vodozemac_wasm.js";
/**
 * Initialize the WASM runtime from the bundled base64 blob.
 * Idempotent — safe to call multiple times; only the first call instantiates.
 * Awaiting this once before constructing Account/Session is required.
 */
export default function init(): Promise<void>;
`,
  "utf8",
);

// ── 4. Package metadata so Metro can resolve the entry ─────────────────────

writeFileSync(
  resolve(pkgRn, "package.json"),
  JSON.stringify(
    {
      type: "module",
      main: "index.js",
      types: "index.d.ts",
      sideEffects: ["./index.js"],
    },
    null,
    2,
  ) + "\n",
  "utf8",
);

console.log(
  `pkg-rn/ built. WASM: ${wasmKb} KB raw → ${b64Kb} KB base64 in JS bundle.`,
);
